[package]
name = "dynamath-core"
version = "0.1.0"
edition = "2021"
description = "Core library for the Dynamath framework"
license = "MIT OR Apache-2.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
